// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const Mongoose = require('mongoose');

const schema = Mongoose.Schema({
  rcUrl: { type: String, required: true },
  resolution: { type: String, required: false },
  test: { type: String, enum: ["banner"], required: true },
  url: { type: String, required: true },
  urlType: {
    type: String,
    enum: ["mobile", "mail", "desktop", "other"],
    required: false,
  },
}, {
  timestamps: false,
});

module.exports = {
  init: (mongoose, Mongoose) => {
    // This section contains the properties of your model, mapped to your collection's properties.
    // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
    return mongoose.model('banners', schema, 'banners');
  },

  schema,
}
