// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const Mongoose = require('mongoose');
const { schema: bannerSchema } = require('./banners');

const schema = Mongoose.Schema({
  banners: [bannerSchema],
}, {
  timestamps: false,
});

module.exports = {
  init: (mongoose, Mongoose) => {
    // This section contains the properties of your model, mapped to your collection's properties.
    // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model


    return mongoose.model('campaigns', schema, 'campaigns');
  },
  schema,
}
